return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "modern",
      icons = {
        breadcrumb = ">",
        separator = "->",
        group = "+",
        mappings = false,
        keys = {
          Up = "Up",
          Down = "Down",
          Left = "Left",
          Right = "Right",
          C = "Ctrl+",
          M = "Alt+",
          D = "Cmd+",
          S = "Shift+",
          CR = "Enter",
          Esc = "Esc",
          ScrollWheelDown = "ScrollDown",
          ScrollWheelUp = "ScrollUp",
          NL = "Enter",
          BS = "Backspace",
          Space = "Space",
          Tab = "Tab",
          F1 = "F1",
          F2 = "F2",
          F3 = "F3",
          F4 = "F4",
          F5 = "F5",
          F6 = "F6",
          F7 = "F7",
          F8 = "F8",
          F9 = "F9",
          F10 = "F10",
          F11 = "F11",
          F12 = "F12",
        },
      },
      spec = {
        { "<leader>f", group = "Find" },
        { "<leader>g", group = "Git" },
        { "<leader>l", group = "LSP" },
        { "<leader>u", group = "UI" },
      },
    },
  },
}
